version: "3.8"
services:
  graphite:
    build:
      context: graphite-env
    networks: 
      - backend
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    image: grafana/grafana
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - graphite
  webui:
    build:
      context: webui
    ports:
      - "8080:5000"
      - "6060:6060"
    networks:
      - backend
      - frontend
    depends_on:
      - graphite
    volumes:
      - ../dataset:/dataset

networks:
  frontend:
  backend: