# docker-compose.yml
version: '3'
services: 
  prometheus: 
    image: prom/prometheus:latest
    user: root
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  python:
    image: docker-test:latest
    ports:
      - "8000:8000"

volumes:
  prometheus_data:
  grafana_data:
