{
 "title": "Bird Calls V5",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bird_name",
    "query": "import \"influxdata/influxdb/schema\"\n\n\nschema.measurementFieldKeys(\n    bucket: \"SharedAirDFW\",\n    measurement: \"MBC001\",\n)"
   },
   {
    "name": "device_name",
    "label": "Device Name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"SharedAirDFW\", tag: \"device_name\")"
   },
   { "name": "Confidence", "label": "Confidence", "query": "0.3, 0.5, 0.65, 0.8, 0.95" }
  ]
 },
 "panels": [
  {
   "title": "Bird Call Occurrences By Species",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MBC001\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r._value >= ${Confidence})\n  |> drop(columns: [\"device_id\", \"device_name\"])\n  |> count()\n  |> group()\n  |> sort(desc: true)\n"
    }
   ]
  },
  { "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Sensor Location",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GPSGPGGA2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitudeCoordinate\" or r[\"_field\"] == \"longitudeCoordinate\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Bird Calls Observed",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MBC001\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r._value >= ${Confidence})\n  |> drop(columns: [\"device_id\", \"device_name\"])\n  |> aggregateWindow(every: 1h, fn: count)\n  |> group()\n  |> aggregateWindow(every: 1h, fn: sum)"
    }
   ]
  }
 ]
}