{
 "title": "ESPEC Chamber Debugging",
 "time": { "from": "2025-03-19T20:04:43.598Z", "to": "2025-03-19T21:47:13.334Z" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Node Name",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"SharedAirDFW\", tag: \"device_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"setValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"setValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processValue\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"setValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processValue\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"setValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG changeID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001CHNG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"changeID\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG changeLabel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001CHNG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"changeLabel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG newValue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001CHNG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"newValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG newValue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001CHNG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"newValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001DAP dapGroup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001DAP\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dapGroup\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG success",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001CHNG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"success\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001DAP enabled",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001DAP\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enabled\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001HMDTY enabled",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enabled\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001HMDTY humidityGroup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidityGroup\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001HMDTY power",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001HMDTY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001DAP humidityGroup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001PRGRM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> rename(columns: {_value: \"programName1\"})\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001PRGRM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> rename(columns: {_value: \"programName2\"})\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001PRGRM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> rename(columns: {_value: \"programName3\"})\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001PRGRM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> rename(columns: {_value: \"programName4\"})\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001PRGRM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName5\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> rename(columns: {_value: \"programName5\"})\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG changeID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNCHG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"changeID\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG changeLabel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNCHG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"changeLabel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG newValue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNCHG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"newValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG iteration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNCHG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iteration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG success",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNCHG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"success\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG humidityStart & humidityEnd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidityStart\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidityEnd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG humidityPadding",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidityPadding\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG humidityIncrement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidityIncrement\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG isForced",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"isForced\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001CHNG majorVariable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"majorVariable\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG waitTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"waitTime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG stillTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"stillTime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG temperatureIncrement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureIncrement\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG humidityStart & humidityEnd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureStart\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureEnd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG temperaturePadding",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNDT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperaturePadding\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG rotuingIteration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNPRG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rotuingIteration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG rotuingLength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNPRG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rotuingLength\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG rotuingLength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNPRG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rotuingPercentage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001RTNCHG success",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001RTNPRG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"success\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Chamber Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"chamberTime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "hostIP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hostIP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS enabled",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enabled\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS operationLabel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 134 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"operationLabel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS program",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"program\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS operation",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"operation\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS programName",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 145 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programName\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS programKey",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programKey\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS programTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programTime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS programStep",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"programStep\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS running",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"running\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001STATUS program_counters",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001STATUS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"program_counters\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001TMPRT power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001TMPRT enabled",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enabled\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001TMPRT processValue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"setValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001TMPRT processValue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 170 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"Mints Anemometer 01\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BTL433ESC001TMPRT temperatureGroup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 177 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTL433ESC001TMPRT\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureGroup\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_time\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}