{
 "title": "Light Debugging",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"SharedAirDFW\", tag: \"device_id\")"
   },
   {
    "name": "device_name",
    "label": "Device Name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"SharedAirDFW\", tag: \"device_name\")"
   },
   { "name": "Confidence", "label": "Birdcall Confidence", "query": "0.3, 0.5, 0.65, 0.8, 0.95" }
  ]
 },
 "panels": [
  {
   "title": "Dom.  Wavelength (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dom.Wavelength\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wavelength Heatmap (MIN001)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"channel360nm\" or r[\"_field\"] == \"channel361nm\" or r[\"_field\"] == \"channel362nm\" or r[\"_field\"] == \"channel363nm\" or r[\"_field\"] == \"channel364nm\" or r[\"_field\"] == \"channel365nm\" or r[\"_field\"] == \"channel367nm\" or r[\"_field\"] == \"channel366nm\" or r[\"_field\"] == \"channel368nm\" or r[\"_field\"] == \"channel369nm\" or r[\"_field\"] == \"channel370nm\" or r[\"_field\"] == \"channel371nm\" or r[\"_field\"] == \"channel372nm\" or r[\"_field\"] == \"channel373nm\" or r[\"_field\"] == \"channel374nm\" or r[\"_field\"] == \"channel375nm\" or r[\"_field\"] == \"channel376nm\" or r[\"_field\"] == \"channel377nm\" or r[\"_field\"] == \"channel378nm\" or r[\"_field\"] == \"channel379nm\" or r[\"_field\"] == \"channel380nm\" or r[\"_field\"] == \"channel381nm\" or r[\"_field\"] == \"channel382nm\" or r[\"_field\"] == \"channel383nm\" or r[\"_field\"] == \"channel384nm\" or r[\"_field\"] == \"channel385nm\" or r[\"_field\"] == \"channel386nm\" or r[\"_field\"] == \"channel387nm\" or r[\"_field\"] == \"channel388nm\" or r[\"_field\"] == \"channel389nm\" or r[\"_field\"] == \"channel390nm\" or r[\"_field\"] == \"channel391nm\" or r[\"_field\"] == \"channel392nm\" or r[\"_field\"] == \"channel393nm\" or r[\"_field\"] == \"channel394nm\" or r[\"_field\"] == \"channel395nm\" or r[\"_field\"] == \"channel396nm\" or r[\"_field\"] == \"channel397nm\" or r[\"_field\"] == \"channel398nm\" or r[\"_field\"] == \"channel399nm\" or r[\"_field\"] == \"channel400nm\" or r[\"_field\"] == \"channel401nm\" or r[\"_field\"] == \"channel402nm\" or r[\"_field\"] == \"channel403nm\" or r[\"_field\"] == \"channel404nm\" or r[\"_field\"] == \"channel405nm\" or r[\"_field\"] == \"channel406nm\" or r[\"_field\"] == \"channel407nm\" or r[\"_field\"] == \"channel408nm\" or r[\"_field\"] == \"channel409nm\" or r[\"_field\"] == \"channel410nm\" or r[\"_field\"] == \"channel411nm\" or r[\"_field\"] == \"channel412nm\" or r[\"_field\"] == \"channel413nm\" or r[\"_field\"] == \"channel414nm\" or r[\"_field\"] == \"channel415nm\" or r[\"_field\"] == \"channel416nm\" or r[\"_field\"] == \"channel417nm\" or r[\"_field\"] == \"channel418nm\" or r[\"_field\"] == \"channel419nm\" or r[\"_field\"] == \"channel420nm\" or r[\"_field\"] == \"channel421nm\" or r[\"_field\"] == \"channel422nm\" or r[\"_field\"] == \"channel423nm\" or r[\"_field\"] == \"channel424nm\" or r[\"_field\"] == \"channel425nm\" or r[\"_field\"] == \"channel426nm\" or r[\"_field\"] == \"channel427nm\" or r[\"_field\"] == \"channel428nm\" or r[\"_field\"] == \"channel429nm\" or r[\"_field\"] == \"channel430nm\" or r[\"_field\"] == \"channel431nm\" or r[\"_field\"] == \"channel432nm\" or r[\"_field\"] == \"channel433nm\" or r[\"_field\"] == \"channel434nm\" or r[\"_field\"] == \"channel435nm\" or r[\"_field\"] == \"channel436nm\" or r[\"_field\"] == \"channel437nm\" or r[\"_field\"] == \"channel438nm\" or r[\"_field\"] == \"channel439nm\" or r[\"_field\"] == \"channel440nm\" or r[\"_field\"] == \"channel441nm\" or r[\"_field\"] == \"channel442nm\" or r[\"_field\"] == \"channel443nm\" or r[\"_field\"] == \"channel444nm\" or r[\"_field\"] == \"channel445nm\" or r[\"_field\"] == \"channel446nm\" or r[\"_field\"] == \"channel447nm\" or r[\"_field\"] == \"channel448nm\" or r[\"_field\"] == \"channel449nm\" or r[\"_field\"] == \"channel450nm\" or r[\"_field\"] == \"channel451nm\" or r[\"_field\"] == \"channel452nm\" or r[\"_field\"] == \"channel453nm\" or r[\"_field\"] == \"channel454nm\" or r[\"_field\"] == \"channel455nm\" or r[\"_field\"] == \"channel456nm\" or r[\"_field\"] == \"channel457nm\" or r[\"_field\"] == \"channel458nm\" or r[\"_field\"] == \"channel459nm\" or r[\"_field\"] == \"channel460nm\" or r[\"_field\"] == \"channel461nm\" or r[\"_field\"] == \"channel462nm\" or r[\"_field\"] == \"channel463nm\" or r[\"_field\"] == \"channel464nm\" or r[\"_field\"] == \"channel465nm\" or r[\"_field\"] == \"channel466nm\" or r[\"_field\"] == \"channel467nm\" or r[\"_field\"] == \"channel468nm\" or r[\"_field\"] == \"channel469nm\" or r[\"_field\"] == \"channel470nm\" or r[\"_field\"] == \"channel471nm\" or r[\"_field\"] == \"channel472nm\" or r[\"_field\"] == \"channel473nm\" or r[\"_field\"] == \"channel474nm\" or r[\"_field\"] == \"channel475nm\" or r[\"_field\"] == \"channel476nm\" or r[\"_field\"] == \"channel477nm\" or r[\"_field\"] == \"channel478nm\" or r[\"_field\"] == \"channel479nm\" or r[\"_field\"] == \"channel480nm\" or r[\"_field\"] == \"channel481nm\" or r[\"_field\"] == \"channel482nm\" or r[\"_field\"] == \"channel483nm\" or r[\"_field\"] == \"channel484nm\" or r[\"_field\"] == \"channel485nm\" or r[\"_field\"] == \"channel486nm\" or r[\"_field\"] == \"channel487nm\" or r[\"_field\"] == \"channel488nm\" or r[\"_field\"] == \"channel489nm\" or r[\"_field\"] == \"channel490nm\" or r[\"_field\"] == \"channel491nm\" or r[\"_field\"] == \"channel492nm\" or r[\"_field\"] == \"channel493nm\" or r[\"_field\"] == \"channel494nm\" or r[\"_field\"] == \"channel495nm\" or r[\"_field\"] == \"channel496nm\" or r[\"_field\"] == \"channel497nm\" or r[\"_field\"] == \"channel498nm\" or r[\"_field\"] == \"channel499nm\" or r[\"_field\"] == \"channel500nm\" or r[\"_field\"] == \"channel501nm\" or r[\"_field\"] == \"channel502nm\" or r[\"_field\"] == \"channel503nm\" or r[\"_field\"] == \"channel504nm\" or r[\"_field\"] == \"channel505nm\" or r[\"_field\"] == \"channel506nm\" or r[\"_field\"] == \"channel507nm\" or r[\"_field\"] == \"channel508nm\" or r[\"_field\"] == \"channel509nm\" or r[\"_field\"] == \"channel510nm\" or r[\"_field\"] == \"channel511nm\" or r[\"_field\"] == \"channel512nm\" or r[\"_field\"] == \"channel513nm\" or r[\"_field\"] == \"channel514nm\" or r[\"_field\"] == \"channel515nm\" or r[\"_field\"] == \"channel516nm\" or r[\"_field\"] == \"channel517nm\" or r[\"_field\"] == \"channel518nm\" or r[\"_field\"] == \"channel519nm\" or r[\"_field\"] == \"channel520nm\" or r[\"_field\"] == \"channel522nm\" or r[\"_field\"] == \"channel521nm\" or r[\"_field\"] == \"channel523nm\" or r[\"_field\"] == \"channel524nm\" or r[\"_field\"] == \"channel525nm\" or r[\"_field\"] == \"channel526nm\" or r[\"_field\"] == \"channel527nm\" or r[\"_field\"] == \"channel528nm\" or r[\"_field\"] == \"channel529nm\" or r[\"_field\"] == \"channel530nm\" or r[\"_field\"] == \"channel531nm\" or r[\"_field\"] == \"channel532nm\" or r[\"_field\"] == \"channel533nm\" or r[\"_field\"] == \"channel534nm\" or r[\"_field\"] == \"channel535nm\" or r[\"_field\"] == \"channel536nm\" or r[\"_field\"] == \"channel537nm\" or r[\"_field\"] == \"channel538nm\" or r[\"_field\"] == \"channel539nm\" or r[\"_field\"] == \"channel540nm\" or r[\"_field\"] == \"channel541nm\" or r[\"_field\"] == \"channel542nm\" or r[\"_field\"] == \"channel543nm\" or r[\"_field\"] == \"channel544nm\" or r[\"_field\"] == \"channel545nm\" or r[\"_field\"] == \"channel546nm\" or r[\"_field\"] == \"channel547nm\" or r[\"_field\"] == \"channel548nm\" or r[\"_field\"] == \"channel549nm\" or r[\"_field\"] == \"channel550nm\" or r[\"_field\"] == \"channel551nm\" or r[\"_field\"] == \"channel552nm\" or r[\"_field\"] == \"channel553nm\" or r[\"_field\"] == \"channel554nm\" or r[\"_field\"] == \"channel555nm\" or r[\"_field\"] == \"channel556nm\" or r[\"_field\"] == \"channel557nm\" or r[\"_field\"] == \"channel558nm\" or r[\"_field\"] == \"channel559nm\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rend {MIN001}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Rend0\" or r[\"_field\"] == \"Rend1\" or r[\"_field\"] == \"Rend10\" or r[\"_field\"] == \"Rend11\" or r[\"_field\"] == \"Rend12\" or r[\"_field\"] == \"Rend13\" or r[\"_field\"] == \"Rend14\" or r[\"_field\"] == \"Rend15\" or r[\"_field\"] == \"Rend2\" or r[\"_field\"] == \"Rend3\" or r[\"_field\"] == \"Rend4\" or r[\"_field\"] == \"Rend5\" or r[\"_field\"] == \"Rend6\" or r[\"_field\"] == \"Rend7\" or r[\"_field\"] == \"Rend8\" or r[\"_field\"] == \"Rend9\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rend {MIN001}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLSFRG001\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2_5\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e064300d6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Illuminance (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Illuminance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Excit. Purity (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ExcitPurity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SPRatio (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPRatio\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Peakwave (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PeakWave\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tcp (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Tcp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ScotopicLux (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ScotopicLux\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "AS7265X",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA410nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA435nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA460nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA485nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA510nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA535nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA560nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA585nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA610nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA645nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA680nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA705nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA730nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA760nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA810nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA860nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA900nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AS7265X\")\n  |> filter(fn: (r) => r[\"_field\"] == \"channelA940nm\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tristimulus (MIN001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MIN001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"XTristimulus\" or r[\"_field\"] == \"YTristimulus\" or r[\"_field\"] == \"ZTristimulus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GUVAS12SDV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GUVAS12SDV2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uvShunt\" or r[\"_field\"] == \"uvBus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "als & uvs (LTR390V2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"001e06453e58\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LTR390V2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uvsRead\" or r[\"_field\"] == \"uvs\" or r[\"_field\"] == \"alsRead\" or r[\"_field\"] == \"als\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}