{
 "title": "OpenAQ Visualizations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average pm1 Concentration",
   "type": "gauge",
   "description": "The national average pm1 concentration of 1000 randomly selected points",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"parameter\"] == \"pm1\")\r\n  |> group()\r\n  |> limit(n: 1000)"
    }
   ]
  },
  {
   "title": "Average pm10 Concentration",
   "type": "gauge",
   "description": "The national average pm10 concentration of 1000 randomly selected points",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"parameter\"] == \"pm10\")\r\n  |> group()\r\n  |> limit(n: 1000)"
    }
   ]
  },
  {
   "title": "Parameter Heat Map (µg/m³)",
   "type": "heatmap",
   "description": "A heat map of various parameters in ten minute intervals in µg/m³",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"µg/m³\")\r\n  |> group(columns: [\"parameter\"])\r\n  |> aggregateWindow(\r\n        column: \"_value\",\r\n        every: 10m,\r\n        fn: mean\r\n    )"
    }
   ]
  },
  {
   "title": "pm1 Heatmap",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"parameter\"] == \"pm1\")\r\n  |> group()\r\n  |> limit(n: 5000)"
    }
   ]
  },
  {
   "title": "Parameter Average Measurements (µg/m³)",
   "type": "timeseries",
   "description": "The hourly national average of parameters in µg/m³",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"µg/m³\")\r\n  |> group(columns: [\"parameter\"])\r\n  |> aggregateWindow(\r\n        column: \"_value\",\r\n        every: 1h,\r\n        fn: mean\r\n    )"
    }
   ]
  },
  {
   "title": "Parameter Average Measurements (ppm)",
   "type": "timeseries",
   "description": "The hourly national average of parameters in ppm",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"ppm\")\r\n  |> group(columns: [\"parameter\"])\r\n  |> aggregateWindow(\r\n        column: \"_value\",\r\n        every: 1h,\r\n        fn: mean\r\n    )"
    }
   ]
  },
  {
   "title": "Highest pm1 Measurements",
   "type": "geomap",
   "description": "The map of the 1000 highest pm1 concentrations in the nation",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"parameter\"] == \"pm1\")\r\n  |> group()\r\n  |> sort(desc: true)\r\n  |> limit(n: 1000)"
    }
   ]
  },
  {
   "title": "Parameter Average Measurements (particles/cm³)",
   "type": "timeseries",
   "description": "The hourly national average of parameters in particles/cm³",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "particles/cm³" } },
   "targets": [
    {
     "query": "from(bucket: \"open-aq\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"particles/cm³\")\r\n  |> group(columns: [\"parameter\"])\r\n  |> aggregateWindow(\r\n        column: \"_value\",\r\n        every: 1h,\r\n        fn: mean\r\n    )"
    }
   ]
  }
 ]
}