{
 "title": "Sensor Information",
 "description": "Display some data about all sensors in one overview - Eric",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Data Staleness per Device",
   "type": "stat",
   "gridPos": { "h": 25, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "now_time = uint(v: now())\n\nfrom(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> last()\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> group(columns: [\"location\"])\n  |> keep(columns: [\"location\", \"_time\"])\n  |> last(column: \"_time\")\n  |> map(fn: (r) => ({ r with staleness: (now_time - uint(v: r._time)) }))\n  |> group()\n  |> sort(columns: [\"location\"])"
    }
   ]
  },
  {
   "title": "Info on Geomaps",
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 25 },
   "options": {
    "content": "Once Geomaps support [data links](https://github.com/grafana/grafana/discussions/43124), make clicking markers link to another dashboard. This will enable users to \"drill down\" into the data. "
   }
  },
  {
   "title": "Explore Sensors",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "// For GPSGPGGA2 and GPSGPRMC2, the \"latitude\" is converted into \"latitudeCoordinate\" for us :)\nGPSGPGGA2andGPSGPRMC2 = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /GPSGPGGA2|GPSGPRMC2/ and r[\"_field\"] =~ /latitudeCoordinate|longitudeCoordinate/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Rename to common name for joining\n  |> rename(columns: {latitudeCoordinate: \"latitude\", longitudeCoordinate: \"longitude\"})\n  // Join everything back into a single table\n  |> group()\n\n// For GPGALR, the longitude/latitude can be taken as-is\nGPGALR = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GPGGALR\" and r[\"_field\"] =~ /latitude|longitude/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Join everything back into a single table\n  |> group()\n\n// GPGALR\n\n// For GPGGA, we need to convert longitude/latitude ourselves :()\nGPGGA = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GPGGA\" and r[\"_field\"] =~ /latitude|longitude/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Divide by 100 to obtain real coordinates\n  |> map(fn: (r) => ({ r with latitude: r.latitude / 100.0, longitude: r.longitude / 100.0 }))\n  // Join everything back into a single table\n  |> group()\n\n// Union all of the GPS coordinate tables together. Basically just does concatination, because they have the same schemas\ncoordinates = union(tables: [GPSGPGGA2andGPSGPRMC2, GPGALR, GPGGA])\n  // Somtimes there are multiple GPS sensors on a single location/device. Take the latest one\n  |> group(columns: [\"location\"])\n  |> last(column: \"_time\")\n  |> group()\n  // We do not care about these rows\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n  // Rename \"measurement\" for better UX\n  |> rename(columns: {_measurement: \"sensor\"})\n  \ncoordinates"
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "// For GPSGPGGA2 and GPSGPRMC2, the \"latitude\" is converted into \"latitudeCoordinate\" for us :)\nGPSGPGGA2andGPSGPRMC2 = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /GPSGPGGA2|GPSGPRMC2/ and r[\"_field\"] =~ /latitudeCoordinate|longitudeCoordinate/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Rename to common name for joining\n  |> rename(columns: {latitudeCoordinate: \"latitude\", longitudeCoordinate: \"longitude\"})\n  // Join everything back into a single table\n  |> group()\n\n// For GPGALR, the longitude/latitude can be taken as-is\nGPGALR = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GPGGALR\" and r[\"_field\"] =~ /latitude|longitude/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Join everything back into a single table\n  |> group()\n\n// GPGALR\n\n// For GPGGA, we need to convert longitude/latitude ourselves :()\nGPGGA = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // Take any processed (i.e. standard format) coordinate fields\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GPGGA\" and r[\"_field\"] =~ /latitude|longitude/)\n  // Only care about most recent report. We do this again, but this one filters out the majority of data and speeds up computation\n  |> last(column: \"_time\")\n  // Pivot and group by location (and time, so the column doesnt go away)\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Divide by 100 to obtain real coordinates\n  |> map(fn: (r) => ({ r with latitude: r.latitude / 100.0, longitude: r.longitude / 100.0 }))\n  // Join everything back into a single table\n  |> group()\n\n// Union all of the GPS coordinate tables together. Basically just does concatination, because they have the same schemas\ncoordinates = union(tables: [GPSGPGGA2andGPSGPRMC2, GPGALR, GPGGA])\n  // Somtimes there are multiple GPS sensors on a single location/device. Take the latest one\n  |> group(columns: [\"location\"])\n  |> last(column: \"_time\")\n  |> group()\n  // We do not care about these rows\n  |> drop(columns: [\"_start\", \"_stop\"])\n  // Rename \"measurement\" for better UX\n  |> rename(columns: {_measurement: \"gps-sensor\", _time: \"gps-updated-time\"})\n\npm = from(bucket: \"SharedAirDFW\")\n  // Limit scope for smaller computation\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] =~ /pm10(_0)?|pm5(_0)?|pm2_5/ )\n  |> last(column: \"_time\")\n  |> pivot(rowKey:[\"location\", \"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  // Rename all pm10 to pm10_0, pm5 to pm5_0\n  |> rename(fn: (column) => (if column == \"pm10\" then \"pm10_0\" else if column == \"pm5\" then \"pm5_0\" else column))\n  |> group(columns: [\"location\"])\n  |> last(column: \"_time\")\n  |> group()\n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> rename(columns: {_measurement: \"pm-sensor\", _time: \"pm-update-time\"})\n\njoin(tables: {a: coordinates, b: pm}, on: [\"location\"])\n"
    }
   ]
  }
 ]
}