{
 "title": "Teledyne-T640",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Device Name",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"SharedAirDFW\", tag: \"device_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "PM Histogram",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin000\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin001\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin002\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin003\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin004\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin005\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin006\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin007\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin008\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin009\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin010\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin011\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin012\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin013\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin014\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin015\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin016\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin017\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin018\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin019\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin020\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin021\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin022\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin023\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin024\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin025\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin026\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin027\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin028\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin029\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin030\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin031\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin032\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin033\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin034\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin035\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin036\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin037\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin038\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin039\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin040\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin041\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin042\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin043\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin044\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin045\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin046\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin047\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin048\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin049\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin050\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin051\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin052\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin053\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin054\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin055\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin056\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin057\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin058\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin059\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin060\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin061\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin062\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin063\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin064\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin065\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin066\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin067\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin068\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin069\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin070\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin071\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin072\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin073\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin074\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin075\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin076\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin077\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin078\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin079\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin080\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin081\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin082\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin083\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin084\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin085\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin086\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin087\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin088\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin089\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin090\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin091\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin092\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin093\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin094\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin095\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin096\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin097\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin098\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin099\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin101\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin102\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin103\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin104\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin105\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin106\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin107\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin108\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin109\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin110\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin111\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin112\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin113\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin114\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin115\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin116\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin117\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin118\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin119\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin120\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin121\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin122\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin123\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin124\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin125\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin126\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin127\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin128\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin129\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin130\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin131\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin132\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin133\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin134\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin135\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin136\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin137\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin138\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin139\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin140\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin141\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin142\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin143\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin144\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin145\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin146\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin147\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin148\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin149\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin150\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin151\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin152\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin153\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin154\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin155\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin156\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin157\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin158\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin159\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin160\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin161\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin162\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin163\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin164\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin165\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin166\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin167\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin168\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin169\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin170\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin171\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin172\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin173\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin174\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin175\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin176\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin177\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin178\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin179\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin180\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin181\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin182\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin183\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin184\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin185\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin186\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin187\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin188\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin189\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin190\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin191\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin192\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin193\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin194\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin195\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin196\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin197\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin198\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin199\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin200\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin201\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin202\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin203\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin204\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin205\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin206\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin207\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin208\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin209\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin210\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin212\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin213\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin214\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin215\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin216\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin217\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin218\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin219\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin220\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin221\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin222\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin223\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin224\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin225\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin226\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin227\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin228\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin229\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin230\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin231\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin232\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin233\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin234\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin235\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin236\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin237\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin238\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin239\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin240\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin241\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin242\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin243\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin244\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin245\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin246\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin247\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin248\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin249\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin250\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin251\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin252\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin253\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin254\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"math\"\r\nfrom(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001HIST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin255\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: math.log10(x: r._value + 1.0) }))\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "T640API001RTPM : Real Time Particulate Matter Concentrations (μg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001RTPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001RTPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2_5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001RTPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "T640API001R1HPM: 1h Avg. Particulate Matter Concentrations (μg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R1HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R1HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2_5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R1HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "T640API001R1HPM: 12h Avg. Particulate Matter Concentrations (μg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R12HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R12HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2_5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R12HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "T640API001R1HPM: 24h Avg. Particulate Matter Concentrations (μg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R24HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R24HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2_5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"SharedAirDFW\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001R24HPM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001CLMA\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001CLMA\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001CLMA\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PUMP PWM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pumpDuty\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P3 Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p3Value\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ledTemp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001CLMA\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ledTemp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Particle Concentration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "#/cm³" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001PHC\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalParticleConc\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Box Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001CLMA\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"boxTemp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ascHeaterDuty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001PV\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ascHeaterDuty\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sample Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640MB001PV\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sampleFlow\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current PmtHv Setting",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"opcSvPmtHvSetting\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001OPCSV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "PMT Setting",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"opcSvPmtCalSetting\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001OPCSV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ascHeaterDuty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"SharedAirDFW\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"opcRtHeaterDuty\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T640API001OPC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}