# docker-compose.yml
# note: we can add restart:always to make the container run on reboot
version: '3'
services: 
  influxdb: 
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - '8086:8086'

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node-red_data:/data

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  node-red_data:
  grafana_data:

