# docker-compose.yml
# note: we can add restart:always to make the container run on reboot
version: '3'
services: 
  influxdb: 
    build: ./influxdb-docker
    image: mints-influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      
  
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:consistent
      - ./ofelia.ini:/etc/ofelia/config.ini:consistent 

  nodered:
    build: ./nodered-docker
    image: mints-nodered
    ports:
      - "1880:1880"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - MQTT_CENTRAL_NODES_USERNAME
      - MQTT_CENTRAL_NODES_PASSWORD
      - MQTT_LORA_NODES_USERNAME
      - MQTT_LORA_NODES_PASSWORD
    depends_on:
      - influxdb

  grafana:
    build: ./grafana-docker
    image: mints-grafana
    ports:
      - "3000:3000"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
    depends_on:
      - influxdb

volumes:
  influxdb_data:
