# docker-compose.yml
# note: we can add restart:always to make the container run on reboot
version: '3'
services: 
  influxdb: 
    build: ./influxdb-docker
    image: custom-influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node-red_data:/data

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  node-red_data:
  grafana_data:

